# These are supported funding model platforms

Currently there aren't any ways to support me, but if you do want to support me, send me an email: atahan@minerva.kgi.edu

I might set up a patreon or similar in the future, so please let me know if you want to support me!
